[package]
name = "sysmon1"
version = "0.1.0"
authors = ["Simon Tharby <simontharby@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
iced = { git = "https://github.com/hecrj/iced.git", features = ["smol"] }
sysinfo = "0.15.3"